
title: My Resume
url: 'http://junlulocky.com'
baseurl: '/' #change it according to your repository name



# Profile information
yourname: Nelsón Romero García  ## put your name
title: 'DATA SCIENCE &amp; WEB DEVELOPER'  ## your title
location: Sonora , Mx


## Social Profiles
facebook: http://www.facebook.com  ## your facebook account url
twitter: http://www.twitter.com  ## your twitter account url
linkedin: https://www.linkedin.com/in/nelsonromerog/ ## your linkedin account url
dribbble: http://www.dribble.com  ## you dribbble account url
foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
